import { useEffect, useState, useRef, type ChangeEvent } from 'react';
import { Editor } from './Editor';
import { Preview } from './Preview';
import { useStudio } from './store';
import { cmToMm, mmToCm, parseCm, placeGrid, type Asset, type Motif, type Project } from './model';
import { readAsset, exportPng, exportPdf, openProject, saveProject } from './files';
import { renderPackaging } from './render';
const backgrounds = Object.values(import.meta.glob('../backgrounds/*.png',{eager:true,query:'?url',import:'default'})) as string[];
type NumberFieldProps={label:string;value:number;onChange:(n:number)=>void;min:number;max:number;step:number;unit:string};
function NumberField({label,value,onChange,min,max,step,unit}:NumberFieldProps){
  const [text,setText]=useState(String(Number(value.toFixed(2)))),[invalid,setInvalid]=useState(false),focused=useRef(false);
  useEffect(()=>{if(!focused.current)setText(String(Number(value.toFixed(2))));},[value]);
  const commit=()=>{focused.current=false;const n=parseCm(text);if(n===null||n<min||n>max){setInvalid(true);setText(String(Number(value.toFixed(2))));}else{setInvalid(false);onChange(n);setText(String(n));}};
  return <label className={`field ${invalid?'invalid':''}`}><span>{label}</span><input type="text" inputMode="decimal" value={text} onFocus={()=>{focused.current=true;}} onChange={e=>{setText(e.target.value);setInvalid(false);}} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}} aria-label={label}/><small>{unit}</small></label>;
}
function editNumber(label:string,value:number,onChange:(n:number)=>void,min:number,max:number,step=0.1,unit='cm'){
  return <NumberField key={label} label={label} value={value} onChange={onChange} min={min} max={max} step={step} unit={unit}/>;
}
function PackPreview({kind}:{kind:'front'|'back'|'band'}){
  const project=useStudio(s=>s.project);const [url,setUrl]=useState('');
  useEffect(()=>{let active=true;const timer=setTimeout(()=>{void renderPackaging(project,kind,65).then(c=>new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(Error('Vorschau fehlgeschlagen'))))).then(b=>{const next=URL.createObjectURL(b);if(active)setUrl(old=>{if(old)URL.revokeObjectURL(old);return next;});else URL.revokeObjectURL(next);}).catch(console.error);},140);return()=>{active=false;clearTimeout(timer);};},[project,kind]);
  return <figure className="packPreview">{url?<img src={url} alt={`${kind} Vorschau`}/>:<div className="packPending">Lade Vorschau…</div>}<figcaption>{kind==='front'?'Vorderseite':kind==='back'?'Rückseite':'Banderole'}</figcaption></figure>;
}
export function App(){
  const project=useStudio(s=>s.project),update=useStudio(s=>s.update),setProject=useStudio(s=>s.setProject),restore=useStudio(s=>s.restore),newSession=useStudio(s=>s.newSession),ready=useStudio(s=>s.ready),undo=useStudio(s=>s.undo),redo=useStudio(s=>s.redo),past=useStudio(s=>s.past),future=useStudio(s=>s.future),selectedId=useStudio(s=>s.selectedId),selectedIds=useStudio(s=>s.selectedIds),select=useStudio(s=>s.select);
  const [tab,setTab]=useState<'pattern'|'packaging'>('pattern'),[advanced,setAdvanced]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[ppi,setPpi]=useState(300),[showNewSession,setShowNewSession]=useState(false),[sessionError,setSessionError]=useState('');
  const [grid,setGrid]=useState({width:30,xGap:10,yGap:10,stagger:20});
  const activeExport=useRef<AbortController|null>(null);
  const selected=project.motifs.find(m=>m.id===selectedId);
  const motifAsset=project.assets.find(a=>a.id===project.motifs.at(-1)?.assetId);
  useEffect(()=>{void restore();},[]);
  async function run(fn:(signal:AbortSignal)=>Promise<void>){if(busy)return;const controller=new AbortController();activeExport.current=controller;setBusy(true);setMessage('Verarbeite Datei…');try{await fn(controller.signal);setMessage('Fertig.');}catch(e){setMessage(e instanceof DOMException&&e.name==='AbortError'?'Abgebrochen.':e instanceof Error?e.message:'Ein Fehler ist aufgetreten.');}finally{activeExport.current=null;setBusy(false);}}
  async function upload(event:ChangeEvent<HTMLInputElement>,purpose:'motif'|'background'|'logo'){
    const file=event.target.files?.[0];if(!file)return;
    await run(async()=>{
      const asset=await readAsset(file);
      update(p=>{
        const assets=[...p.assets,asset];
        if(purpose==='background')return {...p,assets,backgroundAssetId:asset.id};
        if(purpose==='logo')return {...p,assets,packaging:{...p.packaging,logoAssetId:asset.id}};
        const widthMm=30;const motif:Motif={id:crypto.randomUUID(),name:asset.name,assetId:asset.id,xMm:p.tileWidthMm/2,yMm:p.tileHeightMm/2,widthMm,heightMm:widthMm*asset.height/asset.width,rotation:0,opacity:1,visible:true,locked:false};
        select(motif.id);return {...p,assets,motifs:[...p.motifs,motif]};
      });
    });event.target.value='';
  }
  function deleteLayer(id:string){update(p=>({...p,motifs:p.motifs.filter(m=>m.id!==id)}));if(selectedIds.includes(id))select(null);}
  async function startNewSession(){setBusy(true);setSessionError('');try{await newSession();setTab('pattern');setAdvanced(false);setPpi(300);setGrid({width:30,xGap:10,yGap:10,stagger:20});setMessage('Neues Projekt gestartet.');setShowNewSession(false);}catch{setSessionError('Die lokale Sicherung konnte nicht gelöscht werden. Bitte erneut versuchen.');}finally{setBusy(false);}}
  function changeMotif(fn:(m:Motif)=>Motif){if(!selectedId)return;update(p=>({...p,motifs:p.motifs.map(m=>m.id===selectedId?fn(m):m)}));}
  function moveLayer(id:string,delta:number){update(p=>{const list=[...p.motifs],i=list.findIndex(m=>m.id===id),j=i+delta;if(i<0||j<0||j>=list.length)return p;[list[i],list[j]]=[list[j],list[i]];return {...p,motifs:list};});}
  function applyGrid(){if(!motifAsset){setMessage('Bitte zuerst ein Motiv hochladen.');return;}try{const pitchX=grid.width+grid.xGap;const pitchY=grid.width*motifAsset.height/motifAsset.width+grid.yGap;const tileWidthMm=pitchX;const tileHeightMm=pitchY*(grid.stagger%pitchX===0?1:2);if(tileWidthMm>350||tileHeightMm>350)throw new Error('Musterabstände ergeben eine zu große Kachel.');const motifs=placeGrid(motifAsset,tileWidthMm,tileHeightMm,grid.width,grid.xGap,grid.yGap,grid.stagger);update(p=>({...p,tileWidthMm,tileHeightMm,motifs}));select(null);setMessage(`${motifs.length} Motive angeordnet.`);}catch(e){setMessage((e as Error).message);}}
  function updateDimension(key:'sheetWidthMm'|'sheetHeightMm'|'tileWidthMm'|'tileHeightMm',cm:number){update(p=>({...p,[key]:cmToMm(cm)}));}
  function updatePack<K extends keyof Project['packaging']>(key:K,value:Project['packaging'][K]){update(p=>({...p,packaging:{...p.packaging,[key]:value}}));}
  const effectivePpi=selected&&project.assets.find(a=>a.id===selected.assetId)?.width ? Math.round(project.assets.find(a=>a.id===selected.assetId)!.width/(selected.widthMm/25.4)) : null;
  return <div className="appShell">
    <header className="topbar"><div className="brand"><span className="brandMark">B</span><div><strong>bergtuch</strong><small>Musterstudio</small></div></div><nav><button className={tab==='pattern'?'active':''} onClick={()=>setTab('pattern')}>Muster</button><button className={tab==='packaging'?'active':''} onClick={()=>setTab('packaging')}>Banderole</button></nav><div className="headerActions"><button className="newProjectButton" onClick={()=>{setSessionError('');setShowNewSession(true);}} disabled={!ready||busy}>Neues Projekt</button><button onClick={undo} disabled={!past.length}>↶ Rückgängig</button><button onClick={redo} disabled={!future.length}>↷ Wiederholen</button></div></header>
    <main className="layout">
      <aside className="sidebar">
        {tab==='pattern'?<>
          <section><div className="eyebrow">01 · FORMAT</div><h2>Dein Tuch</h2><p>Die Vorschau zeigt die spätere Tuchfläche. Alle Maße gelten für den Druck.</p><div className="fieldGrid">{editNumber('Breite',mmToCm(project.sheetWidthMm),n=>updateDimension('sheetWidthMm',n),18,35)}{editNumber('Höhe',mmToCm(project.sheetHeightMm),n=>updateDimension('sheetHeightMm',n),18,35)}</div></section>
          <section><div className="eyebrow">02 · MOTIV</div><h2>Bild hinzufügen</h2><label className="uploadButton">+ Motiv hochladen<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml,application/pdf" onChange={e=>void upload(e,'motif')}/></label><p className="hint">PNG, JPEG, WebP, SVG oder PDF · bis 30 MB</p><label className="field colorField"><span>Hintergrundfarbe</span><input type="color" value={project.backgroundColor} onChange={e=>update(p=>({...p,backgroundColor:e.target.value}))}/></label><label className="uploadButton secondary">Hintergrundbild<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml,application/pdf" onChange={e=>void upload(e,'background')}/></label><div className="backgrounds">{backgrounds.map((src,i)=><button key={src} title={`Vorlage ${i+1}`} onClick={()=>void run(async()=>{const blob=await (await fetch(src)).blob();const a=await readAsset(new File([blob],`Design ${i+1}.png`,{type:'image/png'}));update(p=>({...p,assets:[...p.assets,a],backgroundAssetId:a.id}));})}><img src={src} alt={`Hintergrund ${i+1}`}/></button>)}</div>{project.backgroundAssetId&&<button className="textButton" onClick={()=>update(p=>({...p,backgroundAssetId:null}))}>Hintergrundbild entfernen</button>}</section>
          <section><div className="eyebrow">03 · WIEDERHOLUNG</div><h2>Nahtlose Kachel</h2><div className="fieldGrid">{editNumber('Kachelbreite',mmToCm(project.tileWidthMm),n=>updateDimension('tileWidthMm',n),0.5,35)}{editNumber('Kachelhöhe',mmToCm(project.tileHeightMm),n=>updateDimension('tileHeightMm',n),0.5,35)}</div><p className="hint">Objekte am Rand werden automatisch auf der Gegenseite fortgesetzt.</p><div className="fieldGrid">{editNumber('Motivbreite',grid.width/10,n=>setGrid({...grid,width:cmToMm(n)}),0.2,30)}{editNumber('Abstand X',grid.xGap/10,n=>setGrid({...grid,xGap:cmToMm(n)}),0,30)}{editNumber('Abstand Y',grid.yGap/10,n=>setGrid({...grid,yGap:cmToMm(n)}),0,30)}{editNumber('Zeilenversatz',grid.stagger/10,n=>setGrid({...grid,stagger:cmToMm(n)}),0,30)}</div><button className="primary" onClick={applyGrid} disabled={!motifAsset}>Als Muster anordnen</button><p className="hint">Die Anordnung ersetzt die Motive auf der Kachel. Rückgängig stellt sie wieder her.</p></section>
          <section><button className="disclosure" onClick={()=>setAdvanced(!advanced)}>Ebene & Details <span>{advanced?'−':'+'}</span></button>{advanced&&<><p className="hint">Mehrere Motive mit Umschalt-Klick auswählen und gemeinsam bewegen.</p><div className="layers">{[...project.motifs].reverse().map(m=><div className={m.id===selectedId?'layer selected':'layer'} key={m.id}><button className="layerName" onClick={()=>select(m.id)}>{m.name}</button><button title="Sichtbarkeit" onClick={()=>update(p=>({...p,motifs:p.motifs.map(x=>x.id===m.id?{...x,visible:!x.visible}:x)}))}>{m.visible?'◉':'○'}</button><button title="Sperren" onClick={()=>update(p=>({...p,motifs:p.motifs.map(x=>x.id===m.id?{...x,locked:!x.locked}:x)}))}>{m.locked?'🔒':'◇'}</button><button title="Nach oben" onClick={()=>moveLayer(m.id,1)}>↑</button><button title="Nach unten" onClick={()=>moveLayer(m.id,-1)}>↓</button><button className="deleteLayerButton" aria-label={`Ebene ${m.name} löschen`} title="Ebene löschen" onClick={()=>deleteLayer(m.id)}>×</button></div>)}</div>{selectedIds.length>1&&<button className="groupButton" onClick={()=>{const groupId=crypto.randomUUID();update(p=>({...p,motifs:p.motifs.map(m=>selectedIds.includes(m.id)?{...m,groupId}:m)}));}}>Gruppe bilden</button>}{selected?.groupId&&<button className="groupButton" onClick={()=>{const groupId=selected.groupId;update(p=>({...p,motifs:p.motifs.map(m=>m.groupId===groupId?{...m,groupId:undefined}:m)}));}}>Gruppe lösen</button>}{selected&&<><h3>Ausgewähltes Motiv</h3><div className="fieldGrid">{editNumber('X',selected.xMm/10,n=>changeMotif(m=>({...m,xMm:cmToMm(n)})),-100,100)}{editNumber('Y',selected.yMm/10,n=>changeMotif(m=>({...m,yMm:cmToMm(n)})),-100,100)}{editNumber('Breite',selected.widthMm/10,n=>changeMotif(m=>({...m,widthMm:cmToMm(n),heightMm:cmToMm(n)*m.heightMm/m.widthMm})),0.2,100)}{editNumber('Drehung',selected.rotation,n=>changeMotif(m=>({...m,rotation:n})),-36000,36000,1,'°')}{editNumber('Deckkraft',selected.opacity*100,n=>changeMotif(m=>({...m,opacity:n/100})),0,100,1,'%')}</div>{effectivePpi!==null&&<p className={effectivePpi<300?'qualityWarning':'hint'}>Bildauflösung bei dieser Größe: ca. {effectivePpi} PPI{effectivePpi<300?' · für 300 PPI kleiner platzieren oder größere Datei wählen':''}</p>}<div className="row"><button onClick={()=>{const copy={...selected,id:crypto.randomUUID(),xMm:selected.xMm+5,yMm:selected.yMm+5};update(p=>({...p,motifs:[...p.motifs,copy]}));select(copy.id);}}>Duplizieren</button><button onClick={()=>deleteLayer(selected.id)}>Ebene löschen</button></div></>}</>}</section>
        </>:<>
          <section><div className="eyebrow">VERPACKUNG</div><h2>Banderole</h2><p>Gestalte Vorderseite, Rückseite und das flache Etikett für dieses Tuch.</p><label className="uploadButton">+ Logo hochladen<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml,application/pdf" onChange={e=>void upload(e,'logo')}/></label><div className="fieldGrid">{editNumber('Logobreite',project.packaging.logoWidthMm/10,n=>updatePack('logoWidthMm',cmToMm(n)),0.2,10)}{editNumber('Drehung',project.packaging.logoRotation,n=>updatePack('logoRotation',n),-36000,36000,1,'°')}{editNumber('Position X',project.packaging.logoXMm/10,n=>updatePack('logoXMm',cmToMm(n)),-20,30)}{editNumber('Position Y',project.packaging.logoYMm/10,n=>updatePack('logoYMm',cmToMm(n)),-20,30)}</div></section><section><h2>Firmendaten</h2>{(['company','street','zip','city'] as const).map((key,i)=><label className="textField" key={key}><span>{['Firma','Straße','PLZ','Ort'][i]}</span><input value={project.packaging[key]} onChange={e=>updatePack(key,e.target.value)}/></label>)}</section>
        </>}
        <section className="exportSection"><div className="eyebrow">DATEIEN</div><h2>Exportieren</h2><p>RGB · Maße 1:1</p><label className="textField">Auflösung <select value={ppi} onChange={e=>setPpi(Number(e.target.value))}><option value={300}>300 PPI · Druck</option><option value={150}>150 PPI · Entwurf</option></select></label><div className="exportGrid">{tab==='pattern'?<><button className="primary" disabled={busy} onClick={()=>void run(signal=>exportPng(project,'sheet',ppi,signal))}>Tuch PNG</button><button disabled={busy} onClick={()=>void run(signal=>exportPdf(project,'sheet',ppi,signal))}>Tuch PDF</button><button disabled={busy} onClick={()=>void run(signal=>exportPng(project,'tile',ppi,signal))}>Kachel PNG</button></>:<>{(['front','back','band'] as const).map(kind=><div className="exportPair" key={kind}><span>{kind==='front'?'Vorderseite':kind==='back'?'Rückseite':'Banderole'}</span><button disabled={busy} onClick={()=>void run(signal=>exportPng(project,kind,ppi,signal))}>PNG</button><button disabled={busy} onClick={()=>void run(signal=>exportPdf(project,kind,ppi,signal))}>PDF</button></div>)}</>}</div><div className="row"><button onClick={()=>void run(()=>saveProject(project))}>Projekt speichern</button><label className="fileButton">Projekt öffnen<input type="file" accept=".zip,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>setProject(await openProject(f)));}}/></label></div><p className="hint">Änderungen werden lokal im Browser gespeichert.</p></section>
      </aside>
      <div className="workspace"><div className="workspaceHeader"><div><div className="eyebrow">{tab==='pattern'?'MUSTERGESTALTUNG':'VERPACKUNGSVORSCHAU'}</div><h1>{tab==='pattern'?'Ein Muster, das weiterläuft.':'Dein Tuch, fertig verpackt.'}</h1></div><span className="sizeBadge">{project.sheetWidthMm/10} × {project.sheetHeightMm/10} cm</span></div>{tab==='pattern'?<div className="canvasGrid"><div><div className="panelHead"><h3>Kachel bearbeiten</h3><span>Motiv ziehen · Ecken skalieren · Drehen</span></div><Editor/></div><div><div className="panelHead"><h3>So wirkt das Tuch</h3><span>Wiederholung in Echtzeit</span></div><Preview/></div></div>:<div className="packGrid"><PackPreview kind="front"/><PackPreview kind="back"/><PackPreview kind="band"/></div>}<div className="status" role="status">{busy&&<button onClick={()=>activeExport.current?.abort()}>Abbrechen</button>}{busy?'◌ ':message?'✓ ':''}{message||'Bereit für dein nächstes Muster.'}</div></div>
    </main>
    {showNewSession&&<div className="dialogBackdrop" role="presentation"><section className="confirmDialog" role="dialog" aria-modal="true" aria-labelledby="new-session-title"><div className="eyebrow">NEUER ENTWURF</div><h2 id="new-session-title">Neues Projekt starten?</h2><p>Der aktuelle Entwurf und die lokale Sicherung werden gelöscht. Speichere dein Projekt vorher, wenn du es später weiterbearbeiten möchtest.</p>{sessionError&&<p role="alert" className="qualityWarning">{sessionError}</p>}<div className="dialogActions"><button disabled={busy} onClick={()=>setShowNewSession(false)}>Abbrechen</button><button className="primary" disabled={busy} onClick={()=>void startNewSession()}>{busy?'Bitte warten…':'Neues Projekt starten'}</button></div></section></div>}
  </div>;
}
