import { chromium } from 'playwright-core';
import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||(existsSync('/usr/bin/chromium')?'/usr/bin/chromium':chromium.executablePath()),headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
try {
  const page=await browser.newPage({acceptDownloads:true,viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.APP_URL||'http://127.0.0.1:5173/');
  await page.getByText('Ein Muster, das weiterläuft.').waitFor();
  await page.getByRole('button',{name:'Ungefähre Originalgröße'}).click();
  await page.locator('.actualScroll canvas').waitFor();
  await page.getByRole('button',{name:'Einpassen'}).click();
  if(await page.locator('.previewCanvas canvas').count()!==1)throw Error('Live preview disappeared after calibration view');
  const file=await readFile(path.join(root,'src/backgrounds/Design_13.png'));
  await page.locator('input[type=file]').first().setInputFiles({name:'motif.png',mimeType:'image/png',buffer:file});
  await page.getByText('Fertig.').waitFor();
  await page.getByRole('button',{name:'Als Muster anordnen'}).click();
  await page.getByText(/Motive angeordnet/).waitFor();
  await page.getByRole('button',{name:/Ebene & Details/}).click();
  await page.waitForTimeout(350);
  const beforeDownload=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Kachel PNG'}).click()]).then(x=>x[0]);
  const beforeTile=await readFile(await beforeDownload.path());
  const upper=await page.locator('.upper-canvas').boundingBox();
  await page.mouse.click(upper.x+45,upper.y+45);
  await page.keyboard.down('Shift');await page.mouse.click(upper.x+130,upper.y+260);await page.keyboard.up('Shift');
  await page.getByRole('button',{name:'Gruppe bilden'}).click({timeout:3000});
  await page.mouse.move(upper.x+130,upper.y+260);await page.mouse.down();await page.mouse.move(upper.x+153,upper.y+270,{steps:4});await page.mouse.up();
  const tile=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Kachel PNG'}).click()]).then(x=>x[0]);
  const tileBytes=await readFile(await tile.path());
  if(tileBytes.subarray(1,4).toString()!=='PNG')throw Error('Tile PNG invalid');
  if(tileBytes.equals(beforeTile))throw Error('Grouped transform did not change repeat export');
  const sheet=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Tuch PNG'}).click()]).then(x=>x[0]);
  const sheetBytes=await readFile(await sheet.path());
  const width=sheetBytes.readUInt32BE(16),height=sheetBytes.readUInt32BE(20);
  if(width!==2953||height!==2953)throw Error(`Wrong sheet pixels ${width}x${height}`);
  const resolutionIndex=sheetBytes.indexOf(Buffer.from('pHYs'));
  if(resolutionIndex<0||sheetBytes.readUInt32BE(resolutionIndex+4)!==11811)throw Error('PNG 300 PPI resolution missing');
  const pdf=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Tuch PDF'}).click()]).then(x=>x[0]);
  const pdfBytes=await readFile(await pdf.path());
  if(pdfBytes.subarray(0,4).toString()!=='%PDF')throw Error('PDF invalid');
  const media=pdfBytes.toString('latin1').match(/\/MediaBox\s*\[\s*0\s+0\s+([\d.]+)\s+([\d.]+)\s*\]/);
  if(!media||Math.abs(Number(media[1])-250/25.4*72)>0.2||Math.abs(Number(media[2])-250/25.4*72)>0.2)throw Error(`Wrong PDF page size: ${media?.[0]}`);
  const edgePixels=await page.evaluate(async()=>{
    const {renderTile}=await import('/src/studio/render.ts');
    const source=document.createElement('canvas');source.width=2;source.height=2;source.getContext('2d').fillStyle='#f00';source.getContext('2d').fillRect(0,0,2,2);
    const p={version:1,sheetWidthMm:250,sheetHeightMm:250,tileWidthMm:100,tileHeightMm:100,backgroundColor:'#fff',backgroundAssetId:null,assets:[{id:'a',name:'a',dataUrl:source.toDataURL(),width:2,height:2}],motifs:[{id:'m',name:'m',assetId:'a',xMm:0,yMm:50,widthMm:20,heightMm:20,rotation:37,opacity:1,visible:true,locked:false}],packaging:{logoAssetId:null,logoWidthMm:30,logoXMm:50,logoYMm:25,logoRotation:0,company:'',street:'',zip:'',city:''}};
    const tile=await renderTile(p,30);const ctx=tile.getContext('2d');return [Array.from(ctx.getImageData(0,Math.round(tile.height/2),1,1).data),Array.from(ctx.getImageData(tile.width-1,Math.round(tile.height/2),1,1).data)];
  });
  if(edgePixels.some(pixel=>pixel[0]<200||pixel[1]>80))throw Error(`Motif did not wrap both sides: ${JSON.stringify(edgePixels)}`);
  await page.getByLabel('Breite',{exact:true}).first().fill('35');await page.getByLabel('Breite',{exact:true}).first().blur();
  await page.getByLabel('Höhe',{exact:true}).fill('18');await page.getByLabel('Höhe',{exact:true}).blur();
  const large=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Tuch PNG'}).click()]).then(x=>x[0]);
  const largeBytes=await readFile(await large.path());
  if(largeBytes.readUInt32BE(16)!==4134||largeBytes.readUInt32BE(20)!==2126)throw Error('Wrong 35x18 cm sheet dimensions');
  const project=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Projekt speichern'}).click()]).then(x=>x[0]);
  const projectBytes=await readFile(await project.path());if(projectBytes.subarray(0,2).toString()!=='PK')throw Error('Project ZIP invalid');
  await page.reload();await page.getByText('35 × 18 cm').first().waitFor();
  await page.locator('input[type=file]').first().setInputFiles({name:'artwork.pdf',mimeType:'application/pdf',buffer:pdfBytes});
  await page.getByText('Fertig.').waitFor({timeout:20000});
  await page.getByRole('button',{name:'Banderole',exact:true}).click();
  await page.getByText('Dein Tuch, fertig verpackt.').waitFor();
  await page.getByText('Vorderseite').first().waitFor();
  await page.waitForFunction(()=>{const images=[...document.querySelectorAll('.packPreview img')];return images.length===3&&images.every(image=>image.complete&&image.naturalWidth>0);},{timeout:10000});
  if(errors.length)throw Error(`Page errors: ${errors.join('; ')}`);
  if(process.env.SCREENSHOT)await page.screenshot({path:process.env.SCREENSHOT,fullPage:true});
  console.log(`Browser smoke passed: tile PNG, 25 cm and 35x18 cm PNG, pHYs, physical PDF, ZIP, autosave, PDF import, packaging. ${tileBytes.length} / ${sheetBytes.length} / ${pdfBytes.length} bytes.`);
} finally {await browser.close();}
